apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: 900653245995.dkr.ecr.ap-south-1.amazonaws.com/cicd/test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
